[project]
name = "baghpat-backend"
version = "0.0.1"
requires-python = ">=3.14"

dependencies = [
    "fastapi[standard]>=0.140.0",
    "uvicorn[standard]==0.35.0",
    "sqlalchemy==2.0.41",
    "psycopg[binary]==3.2.13",
    "pydantic-settings==2.10.1",
    "email-validator==2.2.0",
    "svix==1.96.1",
    "PyJWT[crypto]==2.10.1",
]

[tool.uv]
package = false

[tool.fastapi]
entrypoint = "app.main:app"
